ARG BASE
FROM ${BASE} AS runtime
ARG LIBC_PACKAGE_VERSION
ARG LLVM_PACKAGE_VERSION
RUN apk add --no-cache "musl=$LIBC_PACKAGE_VERSION" "libcxx=$LLVM_PACKAGE_VERSION" "libcxxabi=$LLVM_PACKAGE_VERSION" "libunwind=$LLVM_PACKAGE_VERSION"

FROM runtime AS sdk
ARG LIBC_PACKAGE_VERSION
ARG LLVM_PACKAGE_VERSION
RUN apk add --no-cache "clang=$LLVM_PACKAGE_VERSION" "lld=$LLVM_PACKAGE_VERSION" "llvm-binutils=$LLVM_PACKAGE_VERSION" "musl-devel=$LIBC_PACKAGE_VERSION" "libcxx-devel=$LLVM_PACKAGE_VERSION" "libunwind-devel=$LLVM_PACKAGE_VERSION"
